[build]
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "20"
  AWS_LAMBDA_JS_RUNTIME = "nodejs20.x"

[[redirects]]
  from = "/proxy"
  to = "/.netlify/functions/proxy"
  status = 200
  force = true

[[redirects]]
  from = "/youtube"
  to = "/.netlify/functions/youtube"
  status = 200
  force = true

[[redirects]]
  from = "/audio"
  to = "/.netlify/functions/audio"
  status = 200
  force = true

[[headers]]
  for = "/.netlify/functions/*"
  [headers.values]
    Cache-Control = "public, max-age=300"
